name: Build TZST Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar zstd
        run: sudo apt-get update && sudo apt-get install -y zstd

      - name: Compactar em .tzst
        run: |
          tar --zstd -cf jogos_classicos.tzst "Jogos Classicos"

      - name: Fazer upload do .tzst
        uses: actions/upload-artifact@v3
        with:
          name: JogosClassicos
          path: JogosClassicos.tzst
