name: Build TZST

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Instalar zstd
      run: sudo apt-get install zstd -y
    - name: Compactar pasta para .tzst
      run: tar --zstd -cf jogos_classicos.tzst "Jogos Classicos"
    - name: Fazer upload do .tzst
      uses: actions/upload-artifact@v3
      with:
        name: jogos_classicos
        path: jogos_classicos.tzst
