name: Empacotar Jogos Clássicos

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Compactar pastas dos jogos
        run: |
          powershell Compress-Archive -Path JogosClassicos/* -DestinationPath JogosClassicos.zip

      - name: Enviar APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: JogosClassicos
          path: JogosClassicos.apk
